const { chromium } = require("playwright")

async function main() {
  const b = await chromium.launch()
  const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } })
  const p = await ctx.newPage()
  await p.goto("http://localhost:3000/login", { waitUntil: "networkidle" })
  await p.fill('input[name="identifier"]', "nuttest")
  await p.fill('input[name="password"]', "test1234")
  await p.click('button[type="submit"]')
  await p.waitForURL("**/dashboard", { timeout: 20000 })
  await p.goto("http://localhost:3000/settings", { waitUntil: "networkidle" })
  await p.click('[role="tab"]:has-text("Preferences")')
  await p.waitForTimeout(300)
  const cbs = p.locator('[role="combobox"]')
  console.log("count:", await cbs.count())
  await cbs.nth(0).click()
  await p.click('[role="option"]:has-text("عربي")')
  await p.waitForSelector('[role="option"]', { state: "detached" }).catch(() => {})
  await cbs.nth(1).click()
  await p.click('[role="option"]:has-text("Imperial")')
  await p.waitForSelector('[role="option"]', { state: "detached" }).catch(() => {})
  await cbs.nth(2).click()
  await p.click('[role="option"]:has-text("Monday")')
  await p.waitForSelector('[role="option"]', { state: "detached" }).catch(() => {})
  await cbs.nth(3).click()
  await p.click('[role="option"]:has-text("Africa/Cairo")')
  await p.waitForSelector('[role="option"]', { state: "detached" }).catch(() => {})
  await p.click('button[type="submit"]')
  await p.waitForSelector('html[dir="rtl"]', { timeout: 20000 })
  console.log("now RTL, reloading...")
  await p.reload({ waitUntil: "networkidle" })
  await p.click('[role="tab"]:has-text("التفضيلات")')
  await p.waitForTimeout(500)
  const cbs2 = p.locator('[role="combobox"]')
  console.log("count after reload:", await cbs2.count())
  for (let i = 0; i < (await cbs2.count()); i++) {
    console.log(i, JSON.stringify(await cbs2.nth(i).textContent()))
  }
  await cbs2.nth(3).click()
  await p.waitForTimeout(600)
  console.log("options:", JSON.stringify(await p.locator('[role="option"]').allTextContents()))
  await b.close()
}

main().catch((e) => {
  console.error("FATAL:", e.message)
  process.exit(1)
})
